version: 2

jobs:
  build:
    docker:
      - image: node:16.10.0
    working_directory: ~/demo
    steps:
      - checkout

  pull-and-build:
    docker:
      - image: node:16.10.0
    steps:
      - checkout
      - run:
        name: Run Package
        command: |
          ssh -o StrictHostKeyChecking=no $USER@$IP "./deploy.sh"
