version: 2.1

jobs:
  pull-and-build:
    docker:
      - image: node:16.13.0
    steps:
      - checkout
      - run:
        name: Run Package
        command: |
          ssh -o StrictHostKeyChecking=no $USER@$IP "./deploy.sh"
