version: 2.1

jobs:
  # Job for build for other branches
  build:
    docker:
      - image: cimg/node:16.14.2

    working_directory: ~/demo

    steps:
      - checkout

      - run:
          name: Checking the Node.js version
          command: |
            node --version

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Initializing dependencies
          command: |
            yarn install

      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Build package
          command: |
            yarn build

  # circleci server 8 GB RAM
  resource_class: medium

  # build and deploy to development
  build_and_deploy_to_main:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/demo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Initializing dependencies
          command: |
            yarn install

      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: update gcloud
          command: |
            gcloud components update
      - run:
          name: connect with vm
          command: |
            gcloud compute ssh --project=readytoworkjapan --zone=asia-northeast1-b circlecidemo

      - run:
          name: Build package
          command: |
            yarn build

      - run:
          name: Deploy package
          command: |
            gcloud compute scp package.json circlecidemo:~/demo

  build_and_deploy_to_production:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/demo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Initializing dependencies
          command: |
            yarn install

      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: update gcloud
          command: |
            gcloud components update

      - run:
          name: connect with vm
          command: |
            gcloud compute ssh --project=readytoworkjapan --zone=asia-northeast1-b circlecidemo

      - run:
          name: Build package
          command: |
            yarn build

      - run:
          name: Deploy package
          command: |
            gcloud compute scp package.json circlecidemo:~/demo

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

      - build_and_deploy_to_main:
          filters:
            branches:
              only:
                - main
          requires:
            - build

      - build_and_deploy_to_production:
          filters:
            tags:
              only:
                - /v[0-9].*/
            branches:
              ignore:
                - /.*/
