version: 2
jobs:
  build:
    docker:
      - image: node:16.13.0
    working_directory: ~/repo
    step:
      - checkout
      # Download and cache dependicies
      - restore_cache:
        keys:
          - v1-dependencies-{{checksum "package.json"}}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependicies -{{checksum "package.json"}}

      # run tests
      - run: yarn test
      - run: yarn build
      - run: yarn netlify:deploy
