version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: node:16.10.0
    working_directory: ~/demo
    steps:
      - checkout
      - run:
          name: Get and install node version manager.
          command: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

      - run:
          name: Use Node version 12
          command: source ~/.profile

      - run:
          name: Install Node version 16.10.0 using NVM
          command: nvm install 16.10.0

      - run:
          name: Run package
          command: |
            ssh -o StrictHostKeyChecking=no $USER@$ID "./demo/demo_deploy.sh"
# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
