version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: node:16.10.0
    working_directory: ~/demo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - run:
          name: Checking the Node.js version
          command: |
            node --version
      - save_cache:
          paths:
            - node_modules
          key: v1-dependicies -{{checksum "package.json"}}

      - run: yarn build
      - run:
          name: Run package
          command: |
            ssh -o StrictHostKeyChecking=no $USER@$ID "./demo/demo_deploy.sh"
# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
