version: 2.1

jobs:
  # Job for build for other branches
  build:
    docker:
      - image: cimg/node:16.14.2

    working_directory: ~/demo

    steps:
      - checkout

      - run:
          name: Checking the Node.js version
          command: |
            node --version

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Initializing dependencies
          command: |
            yarn install

      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Build package
          command: |
            yarn build

  # circleci server 8 GB RAM
  resource_class: medium

  # build and deploy to development
  build_and_deploy_to_main:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/demo

    steps:
      - checkout
      - node/install:
          install-yarn: true
          lts: true

      - run:
          name: Checking Node.JS version
          command: |
            node --version
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Initializing dependencies
          command: |
            yarn install
      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Authenticating and configuring the Google Cloud Platform
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GCLOUD_ZONE}

      - run:
          name: Build package
          command: |
            yarn build

      - run:
          name: Deploy package
          command: |
            pwd
            gcloud --quiet compute scp --recurse --compress  .next public package.json yarn.lock deploy_demo.sh  circlecidemo:/home/bebika_singh/demo  --strict-host-key-checking=no
            chmod u+x ./deploy_demo.sh
            pwd
            /home/bebika_singh/demo/deploy_demo.sh

# Orchestrate our job run sequence
orbs:
  node: circleci/node@4.7.0
workflows:
  version: 2
  build-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

      - build_and_deploy_to_main:
          filters:
            branches:
              only:
                - main
