version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/demo
    steps:
      - checkout

      - run:
          name: Run package
          command: |
            ssh -o StrictHostKeyChecking=no $USER@$ID "./demo/demo_deploy.sh"
# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
