version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/demo
    steps:
      - checkout
      # - run:
      #     name: Run package
      #     command: |
      #       ssh -o StrictHostKeyChecking=no bebika@circlecidemo "./demo/deploy_demo.sh"
      - run:
          name: Checking the Node.js version
          command: |
            node --version

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Initializing dependencies
          command: |
            yarn install

      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run:
          name: Build package
          command: |
            yarn build

      - run:
          name: Deploy package
          command: |
            scp -r -o StrictHostKeyChecking=no build public package.json yarn.lock deploy_demo.sh bebika@circlecidemo:"/home/circleci/demo/"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
