version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: node:16.10.0
    working_directory: ~/demo
    steps:
      - checkout
      - run: ssh -o StrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
